
package metodosnumericos;
import javax.swing.JOptionPane;
import org.nfunk.jep.ParseException;

public class Secante extends javax.swing.JFrame {

    private Funcion F;
    
    public Secante() {
        initComponents();
        setLocationRelativeTo(null);
        fun.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        fun = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtx0 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtx1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Res = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método de la Secante");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese Función");

        fun.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        fun.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        salir.setText("REGRESAR");
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Borrar.setText("Eliminar funcion");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("X1");

        txtx0.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        txtx0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtx0.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtx0.setName("txtx0"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("X0");

        txtx1.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        txtx1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Res.setEditable(true);
        Res.setColumns(20);
        Res.setFont(new java.awt.Font("Ubuntu Light", 1, 15));
        Res.setRows(5);
        jScrollPane1.setViewportView(Res);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                    .addComponent(Borrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtx0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtx1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fun, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(fun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtx0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        if(evt.getSource() == salir){	
            MenuMetodos abrir=new MenuMetodos();
            abrir.setVisible(true);
            this.setVisible(false);
	}
    }//GEN-LAST:event_salirActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        double x = 0, x0 = 0, x1 = 0, ER = 0;
        int max = 0, dec = 0;
    
        Res.setText(null);
        F = new Funcion(fun.getText());
        x = 0;
        int i = 1;
        String r = "";
        boolean si = true;
        double tol = 0;
        max = 0;
        double fx0 = 0, fx1 = 0, fx = 0;

        do {
            try {
                if (i == 1) {
                    x0 = Double.parseDouble(txtx0.getText());
                    x1 = Double.parseDouble(txtx1.getText());
                    x = x1;
                    dec = F.decimales();
                    if (F.menu() == 1) {
                        max = F.iteraciones();
                    } else {
                        tol = F.tolerancia();
                    }
                }
                fx0 = F.Redondear(F.Evaluar(x0), dec);
                fx1 = F.Redondear(F.Evaluar(x1), dec);
                double xAnt = x;
                x = F.Redondear(x1 - ((fx1 * (x0 - x1)) / (fx0 - fx1)), dec);
                fx = F.Redondear(F.Evaluar(x), (dec+1));
                ER = F.Redondear(Math.abs((x - xAnt) / x), dec > 10 ? dec : 8);
                if (max > 1 || (ER > tol && tol != 0)) {
                    x0 = x1;
                    x1 = x;
                }
                if(ER == 0){
                    max = 0;
                    tol = 0;
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Función Incorrecta", "ERROR", 0);
                max = 0;
                tol = 0;
                fun.requestFocus();
                si = false;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valores limites Incorrectos", "ERROR", 0);
                max = 0;
                tol = 0;
                txtx0.setText(null);
                txtx1.setText(null);
                txtx0.requestFocus();
                si = false;
            }
            i++;
            if (tol == 0) {
                max--;
            } else if (ER < tol && i != 2) {
                tol = 0;
            }
            r += ("Iteración: " + (i-1) + "  |  Xi-1: " + x0 + "  |  Xi: " + x1 + "  |  F(Xi-1): " + fx0 + "  |  F(Xi): " + fx1 
                + "  |  F((Xi-1)-Xi): " + fx + "  |  Xi+1: " + x + "  |  E.R: " + ER + "\n\n");
        } while (max > 0 || tol > 0 && i < 500);
        if (i == 500)
            r = "La Función Diverge\n\n";
        if (si) {
            JOptionPane.showMessageDialog(null, "Iteraciones Finalizadas", "Resultados", JOptionPane.INFORMATION_MESSAGE);
            Res.setText(r + "\nRespuesta Aproximada\nX =  " + x);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        Res.setText(null);
        txtx1.setText(null);
        txtx0.setText(null);
        fun.setText(null);
        fun.requestFocus();
    }//GEN-LAST:event_BorrarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Borrar;
    private javax.swing.JTextArea Res;
    private javax.swing.JTextField fun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtx0;
    private javax.swing.JTextField txtx1;
    // End of variables declaration//GEN-END:variables
}
